var searchData=
[
  ['zdotc_5f',['zdotc_',['../blas__wrapper_8hpp.html#a399a2ffb62fc4bdad21ea915cb0659e9',1,'zdotc_(dcmplx *RETURN, int *N, dcmplx *ZX, int *INCX, dcmplx *ZY, int *INCY):&#160;blas_wrapper.hpp'],['../blas__wrapper_8hpp.html#a70bdc281f384e35f2b580f15dc18dbeb',1,'zdotc_(double *RETURN, int *N, double *ZX, int *INCX, double *ZY, int *INCY):&#160;blas_wrapper.hpp']]],
  ['zdscal_5f',['zdscal_',['../blas__wrapper_8hpp.html#a71a6a9b1dacbff5e2ecac04c2e566b88',1,'zdscal_(int *N, double *ALPHA, dcmplx *X, int *INCX):&#160;blas_wrapper.hpp'],['../blas__wrapper_8hpp.html#ab36cfa1f314d9cb4c2f069482a307f7e',1,'zdscal_(int *N, double *ALPHA, double *X, int *INCX):&#160;blas_wrapper.hpp']]],
  ['zgeev_5f',['zgeev_',['../lapack__wrapper_8hpp.html#afc76eb0913fc08074e087206c407c665',1,'zgeev_(char *JOBVL, char *JOBVR, int *N, dcmplx *A, int *LDA, dcmplx *W, dcmplx *VL, int *LDVL, dcmplx *VR, int *LDVR, dcmplx *WORK, int *LWORK, int *INFO):&#160;lapack_wrapper.hpp'],['../lapack__wrapper_8hpp.html#aab22d8e16079d6751a33946daf79caa5',1,'zgeev_(char *JOBVL, char *JOBVR, int *N, double *A, int *LDA, dcmplx *W, double *VL, int *LDVL, double *VR, int *LDVR, double *WORK, int *LWORK, int *INFO):&#160;lapack_wrapper.hpp']]],
  ['zgeqrf_5f',['zgeqrf_',['../lapack__wrapper_8hpp.html#aba79bcd45764da41b1e4a9e687c2265b',1,'zgeqrf_(int *M, int *N, dcmplx *A, int *LDA, dcmplx *TAU, dcmplx *WORK, int *LWORK, int *INFO):&#160;lapack_wrapper.hpp'],['../lapack__wrapper_8hpp.html#a7db194ce69f25f508b41cdfa182f6051',1,'zgeqrf_(int *M, int *N, double *A, int *LDA, double *TAU, double *WORK, int *LWORK, int *INFO):&#160;lapack_wrapper.hpp']]],
  ['zgesvd_5f',['zgesvd_',['../lapack__wrapper_8hpp.html#aa3538d91a38839c87192428b90e1c671',1,'zgesvd_(char *JOBU, char *JOBVT, int *M, int *N, dcmplx *A, int *LDA, double *S, dcmplx *U, int *LDU, dcmplx *VT, int *LDVT, dcmplx *WORK, int *LWORK, double *RWORK, int *INFO):&#160;lapack_wrapper.hpp'],['../lapack__wrapper_8hpp.html#a3f910de9d3965644a270ef0f665f2925',1,'zgesvd_(char *JOBU, char *JOBVT, int *M, int *N, double *A, int *LDA, double *S, double *U, int *LDU, double *VT, int *LDVT, double *WORK, int *LWORK, double *RWORK, int *INFO):&#160;lapack_wrapper.hpp']]],
  ['zheevr_5f',['zheevr_',['../lapack__wrapper_8hpp.html#a0b3c111fa5cfbf49a332688cb65fef96',1,'zheevr_(char *JOBZ, char *RANGE, char *UPLO, int *N, dcmplx *A, int *LDA, double *VL, double *VU, int *IL, int *IU, double *ABSTOL, int *M, double *W, dcmplx *Z, int *LDZ, int *ISUPPZ, dcmplx *WORK, int *LWORK, double *RWORK, int *LRWORK, int *IWORK, int *LIWORK, int *INFO):&#160;lapack_wrapper.hpp'],['../lapack__wrapper_8hpp.html#af89487ffcd54fb3a9f83856715359cbc',1,'zheevr_(char *JOBZ, char *RANGE, char *UPLO, int *N, double *A, int *LDA, double *VL, double *VU, int *IL, int *IU, double *ABSTOL, int *M, double *W, double *Z, int *LDZ, int *ISUPPZ, double *WORK, int *LWORK, double *RWORK, int *LRWORK, int *IWORK, int *LIWORK, int *INFO):&#160;lapack_wrapper.hpp']]],
  ['znaupd_5f',['znaupd_',['../arpack__wrapper_8hpp.html#a5e362d6a0890ddc0836d667498fefd54',1,'znaupd_(int *IDO, char *BMAT, int *N, char *WHICH, int *NEV, double *TOL, dcmplx *RESID, int *NCV, dcmplx *V, int *LDV, int *IPARAM, int *IPNTR, dcmplx *WORKD, dcmplx *WORKL, int *LWORKL, double *RWORK, int *INFO, int *LEN_BMAT, int *LEN_WHICH):&#160;arpack_wrapper.hpp'],['../arpack__wrapper_8hpp.html#aec17ed55ba52fcc958283eb1afd4dd11',1,'znaupd_(int *IDO, char *BMAT, int *N, char *WHICH, int *NEV, double *TOL, double *RESID, int *NCV, double *V, int *LDV, int *IPARAM, int *IPNTR, double *WORKD, double *WORKL, int *LWORKL, double *RWORK, int *INFO, int *LEN_BMAT, int *LEN_WHICH):&#160;arpack_wrapper.hpp']]],
  ['zneupd_5f',['zneupd_',['../arpack__wrapper_8hpp.html#acf9b4732a72951a62b54b3fcd13dc845',1,'zneupd_(int *RVEC, char *HOWMNY, int *SELECT, dcmplx *D, dcmplx *Z, int *LDZ, dcmplx *SIGMA, dcmplx *WORKEV, char *BMAT, int *N, char *WHICH, int *NEV, double *TOL, dcmplx *RESID, int *NCV, dcmplx *V, int *LDV, int *IPARAM, int *IPNTR, dcmplx *WORKD, dcmplx *WORKL, int *LWORKL, double *RWORK, int *INFO, int *LEN_HOWMNY, int *LEN_BMAT, int *LEN_WHICH):&#160;arpack_wrapper.hpp'],['../arpack__wrapper_8hpp.html#ab806e49fd9138e10e305bb229802622c',1,'zneupd_(int *RVEC, char *HOWMNY, int *SELECT, double *D, double *Z, int *LDZ, double *SIGMA, double *WORKEV, char *BMAT, int *N, char *WHICH, int *NEV, double *TOL, double *RESID, int *NCV, double *V, int *LDV, int *IPARAM, int *IPNTR, double *WORKD, double *WORKL, int *LWORKL, double *RWORK, int *INFO, int *LEN_HOWMNY, int *LEN_BMAT, int *LEN_WHICH):&#160;arpack_wrapper.hpp']]],
  ['zungqr_5f',['zungqr_',['../lapack__wrapper_8hpp.html#a48bb95b4109997291380f9aebc7511f6',1,'zungqr_(int *M, int *N, int *K, dcmplx *A, int *LDA, dcmplx *TAU, dcmplx *WORK, int *LWORK, int *INFO):&#160;lapack_wrapper.hpp'],['../lapack__wrapper_8hpp.html#a372bc4088426b34c57460734568acf00',1,'zungqr_(int *M, int *N, int *K, double *A, int *LDA, double *TAU, double *WORK, int *LWORK, int *INFO):&#160;lapack_wrapper.hpp']]]
];
